// <auto-generated />
using System;
using Elp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421103813_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elp.Domain.Entities.Codebook", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameCz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Codebooks");

                    b.HasData(
                        new
                        {
                            Code = "akce_ro",
                            NameCz = "akce ro",
                            NameEn = "event"
                        },
                        new
                        {
                            Code = "druh_prohlidky_ro",
                            NameCz = "druh prohlidky ro",
                            NameEn = "type of inspection"
                        },
                        new
                        {
                            Code = "skupina_ro",
                            NameCz = "skupina ro",
                            NameEn = "group"
                        },
                        new
                        {
                            Code = "vysledek_posudku_ro",
                            NameCz = "vysledek posudku ro",
                            NameEn = "assessment result"
                        },
                        new
                        {
                            Code = "druh_posudku_ro",
                            NameCz = "druh posudku ro",
                            NameEn = "assessment type"
                        },
                        new
                        {
                            Code = "seznam_skupin_ro",
                            NameCz = "seznam skupin",
                            NameEn = "vehicle type"
                        },
                        new
                        {
                            Code = "seznam_harmonizovane_kody_ro",
                            NameCz = "harmonizovane kody",
                            NameEn = "harmonized codes"
                        },
                        new
                        {
                            Code = "seznam_narodni_kody_ro",
                            NameCz = "harmonizovane kody",
                            NameEn = "country codes"
                        },
                        new
                        {
                            Code = "stav_posudku",
                            NameCz = "stav posudku",
                            NameEn = "assessment status"
                        });
                });

            modelBuilder.Entity("Elp.Domain.Entities.CodebookItem", b =>
                {
                    b.Property<string>("CodebookCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescriptionCz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CodebookCode", "Code");

                    b.ToTable("CodebookItems");

                    b.HasData(
                        new
                        {
                            CodebookCode = "akce_ro",
                            Code = "akce_ro_1",
                            DescriptionCz = "vytvoření",
                            DescriptionEn = "creation",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "akce_ro",
                            Code = "akce_ro_2",
                            DescriptionCz = "aktualizace",
                            DescriptionEn = "update",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "akce_ro",
                            Code = "akce_ro_3",
                            DescriptionCz = "zneplatnění",
                            DescriptionEn = "invalidation",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_prohlidky_ro",
                            Code = "druh_prohlidky_ro3",
                            DescriptionCz = "mimořádná",
                            DescriptionEn = "extraordinary",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_prohlidky_ro",
                            Code = "druh_prohlidky_ro2",
                            DescriptionCz = "pravidelná",
                            DescriptionEn = "regular",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_prohlidky_ro",
                            Code = "druh_prohlidky_ro1",
                            DescriptionCz = "vstupní",
                            DescriptionEn = "input",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "skupina_ro",
                            Code = "skupina_ro_1",
                            DescriptionCz = "skupina 1",
                            DescriptionEn = "group 1",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "skupina_ro",
                            Code = "skupina_ro_2",
                            DescriptionCz = "skupina 2",
                            DescriptionEn = "group 2",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "vysledek_posudku_ro",
                            Code = "vysledek_posudku_ro_1",
                            DescriptionCz = "způsobilý",
                            DescriptionEn = "eligible",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "vysledek_posudku_ro",
                            Code = "vysledek_posudku_ro_2",
                            DescriptionCz = "nezpůsobilý",
                            DescriptionEn = "unqualified",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "vysledek_posudku_ro",
                            Code = "vysledek_posudku_ro_3",
                            DescriptionCz = "způsobilý s podmínkou",
                            DescriptionEn = "eligible with conditions",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_posudku_ro",
                            Code = "druh_posudku_ro_2",
                            DescriptionCz = "rozšíření řidičského oprávnění",
                            DescriptionEn = "Driver's license extension",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_posudku_ro",
                            Code = "druh_posudku_ro_1",
                            DescriptionCz = "prvořidič",
                            DescriptionEn = "lead driver",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_posudku_ro",
                            Code = "druh_posudku_ro_4",
                            DescriptionCz = "senioři",
                            DescriptionEn = "seniors",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_posudku_ro",
                            Code = "druh_posudku_ro_3",
                            DescriptionCz = "prodloužení řidičského oprávnění",
                            DescriptionEn = "renewal of a driver's license",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "druh_posudku_ro",
                            Code = "druh_posudku_ro_5",
                            DescriptionCz = "přezkoumání způsobilosti",
                            DescriptionEn = "eligibility review",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "B",
                            DescriptionCz = "skupina B",
                            DescriptionEn = "Group B",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "A",
                            DescriptionCz = "skupina A",
                            DescriptionEn = "Group A",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "D",
                            DescriptionCz = "skupina D",
                            DescriptionEn = "Group D",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "BE",
                            DescriptionCz = "skupina BE",
                            DescriptionEn = "Group BE",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "C",
                            DescriptionCz = "skupina C",
                            DescriptionEn = "Group C",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "DE",
                            DescriptionCz = "skupina DE",
                            DescriptionEn = "Group DE",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "CE",
                            DescriptionCz = "skupina CE",
                            DescriptionEn = "Group CE",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "D1",
                            DescriptionCz = "skupina D1",
                            DescriptionEn = "Group D1",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "C1",
                            DescriptionCz = "skupina C1",
                            DescriptionEn = "Group C1",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "C1E",
                            DescriptionCz = "skupina C1E",
                            DescriptionEn = "Group C1E",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "AM",
                            DescriptionCz = "skupina AM",
                            DescriptionEn = "Group AM",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "T",
                            DescriptionCz = "skupina T",
                            DescriptionEn = "Group T",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "A2",
                            DescriptionCz = "skupina A2",
                            DescriptionEn = "Group A2",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "B1",
                            DescriptionCz = "skupina B1",
                            DescriptionEn = "Group B1",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_skupin_ro",
                            Code = "A1",
                            DescriptionCz = "skupina A1",
                            DescriptionEn = "Group A1",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "43.01",
                            DescriptionCz = "43.01 Výška sedadla řidiče umožňující normální výhled a v normální vzdálenosti od  volantu a pedálů",
                            DescriptionEn = "43.01 Driver's seat height allowing normal view and at a normal distance from the steering wheel and pedals",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "10.02",
                            DescriptionCz = "10.02 Automatická převodovka",
                            DescriptionEn = "10.02 Automatic transmission",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "10.04",
                            DescriptionCz = "10.04 Přizpůsobené ústrojí ovládání převodovky",
                            DescriptionEn = "10.04 Adapted transmission control mechanism",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "20.07",
                            DescriptionCz = "20.07 Ovládání brzdy s použitím maximální síly ... N [například: 20.07(300 N)]",
                            DescriptionEn = "20.07 Brake operation using a maximum force of ... N [for example: 20.07(300 N)]",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "25.09",
                            DescriptionCz = "25.09 Opatření proti zablokování nebo aktivaci akcelerátoru",
                            DescriptionEn = "25.09 Measures against blocking or activating the accelerator",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "35.05",
                            DescriptionCz = "35.05 Ovladače ovladatelné bez puštění zařízení pro řízení vozidla a mechanismy akcelerátoru a brzd",
                            DescriptionEn = "35.05 Controls operable without releasing the steering device and accelerator and brake mechanisms",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "20.03",
                            DescriptionCz = "20.03 Brzdový pedál upravený na levou nohu",
                            DescriptionEn = "20.03 Brake pedal adapted for the left foot",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "31.04",
                            DescriptionCz = "31.04 Zvýšená podlaha",
                            DescriptionEn = "31.04 Raised floor",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "25.01",
                            DescriptionCz = "25.01 Přizpůsobený pedál akcelerátoru",
                            DescriptionEn = "25.01 Adapted accelerator pedal",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "44.02",
                            DescriptionCz = "44.02 Přizpůsobená brzda na předním kole",
                            DescriptionEn = "44.02 Adapted front wheel brake",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "42.05",
                            DescriptionCz = "42.05 Zařízení k eliminaci mrtvého úhlu",
                            DescriptionEn = "42.05 Device to eliminate blind spots",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "42.01",
                            DescriptionCz = "42.01 Přizpůsobené zařízení pro výhled dozadu",
                            DescriptionEn = "42.01 Adapted rear-view device",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "25.05",
                            DescriptionCz = "25.05 Ovládání akcelerátoru kolenem",
                            DescriptionEn = "25.05 Knee-operated accelerator",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "44.10",
                            DescriptionCz = "44.10 Maximální ovládací síla brzdy zadního kola... N [například 44.10 (240 N)]",
                            DescriptionEn = "44.10 Maximum operating force of the rear wheel brake... N [for example 44.10 (240 N)]",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "63",
                            DescriptionCz = "63. Řízení vozidla bez cestujících",
                            DescriptionEn = "63. Driving a vehicle without passengers",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "64",
                            DescriptionCz = "64. Jízda rychlostí nepřesahující ... km/h",
                            DescriptionEn = "64. Driving at a speed not exceeding ... km/h",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "61",
                            DescriptionCz = "61. Omezení jízdy podle denní doby (například: jedna hodina po východu slunce a jedna hodina před západem slunce)",
                            DescriptionEn = "61. Driving restriction by time of day (for example: one hour after sunrise and one hour before sunset)",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "62",
                            DescriptionCz = "62. Omezení jízdy v okruhu ... km od místa bydliště řidiče nebo pouze ve městě/regionu",
                            DescriptionEn = "62. Driving restriction within a radius of ... km from the driver's place of residence or only within a city/region",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "40.05",
                            DescriptionCz = "40.05 Přizpůsobený volant (větší nebo silnější volant, zmenšený průměr volantu, apod.)",
                            DescriptionEn = "40.05 Adapted steering wheel (larger or thicker steering wheel, reduced steering wheel diameter, etc.)",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_harmonizovane_kody_ro",
                            Code = "67",
                            DescriptionCz = "67. Zákaz jízdy na dálnici",
                            DescriptionEn = "67. Driving on motorways prohibited",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "185",
                            DescriptionCz = "185. Pouze pro řízení motorových vozidel stanovených v § 83 odst. 5 zákona č. 361/2000 Sb. do doby dosažení věku u skupiny vozidel C 21 let, u skupiny vozidel D 24 let",
                            DescriptionEn = "185. Only for driving motor vehicles specified in Section 83, Paragraph 5 of Act No. 361/2000 Coll. until reaching the age of 21 for vehicle category C, and 24 for vehicle category D",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "111a",
                            DescriptionCz = "111. Nelze vykonávat činnost: a) řidiče, který řídí motorové vozidlo v pracovněprávním vztahu a u něhož je řízení motorového vozidla druhem práce sjednaným v pracovní smlouvě",
                            DescriptionEn = "111. Cannot perform the activity of: a) a driver who drives a motor vehicle in an employment relationship and for whom driving a motor vehicle is the type of work agreed upon in the employment contract",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "111b",
                            DescriptionCz = "111. Nelze vykonávat činnost: b) řidiče, u kterého je řízení motorového vozidla předmětem samostatné výdělečné činnosti prováděné podle jiného právního předpisu",
                            DescriptionEn = "111. Cannot perform the activity of: b) a driver for whom driving a motor vehicle is the subject of self-employment carried out under another legal regulation",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "175",
                            DescriptionCz = "175. Omezení řidičského oprávnění skupiny vozidel D pouze k řízení vozidla městské hromadné dopravy osob",
                            DescriptionEn = "175. Restriction of the driving license for vehicle category D only to driving a public transport vehicle",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "111c",
                            DescriptionCz = "111. Nelze vykonávat činnost: c) učitele výcviku v řízení motorových vozidel podle jiného právního předpisu",
                            DescriptionEn = "111. Cannot perform the activity of: c) a driving school instructor under another legal regulation",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "160",
                            DescriptionCz = "160. Výjimka z věku u řidičského oprávnění skupiny vozidel A1, A2 nebo A osoby, která je držitelem licence motoristického sportovce, udělená pouze pro jízdu při sportovní soutěži",
                            DescriptionEn = "160. Age exemption for a driving license of vehicle category A1, A2 or A for a person holding a motorsport athlete license, granted only for driving during a sports competition",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "172",
                            DescriptionCz = "172. Omezení řidičského oprávnění skupiny vozidel A pouze k řízení motorového vozíku pro invalidy",
                            DescriptionEn = "172. Restriction of the driving license for vehicle category A only to driving a motorized wheelchair for the disabled",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "115",
                            DescriptionCz = "115. Posilovač spojky",
                            DescriptionEn = "115. Power clutch",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "105",
                            DescriptionCz = "105. Jiná zdravotní omezení, která nejsou uvedena v části I této přílohy",
                            DescriptionEn = "105. Other health restrictions not listed in Part I of this Annex",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "seznam_narodni_kody_ro",
                            Code = "199",
                            DescriptionCz = "199. Zkušební doba podmíněného upuštění od výkon",
                            DescriptionEn = "199. Probationary period of conditional waiver of execution",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "stav_posudku",
                            Code = "stav_posudku_1",
                            DescriptionCz = "platný",
                            DescriptionEn = "valid",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "stav_posudku",
                            Code = "stav_posudku_2",
                            DescriptionCz = "zneplatněný",
                            DescriptionEn = "invalidated",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "stav_posudku",
                            Code = "stav_posudku_3",
                            DescriptionCz = "neplatný",
                            DescriptionEn = "invalid",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Elp.Domain.Entities.DriverFitnessCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicalProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverFitnessCertificates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IssueDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PersonalId = "ABC-123-456",
                            StatusCode = "stav_posudku_1"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            IssueDate = new DateTime(2026, 2, 10, 9, 30, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PersonalId = "XYZ-987-654",
                            StatusCode = "stav_posudku_3"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            IssueDate = new DateTime(2020, 5, 20, 14, 15, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PersonalId = "ABC-123-456",
                            StatusCode = "stav_posudku_2"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            IssueDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PersonalId = "LMN-456-789",
                            StatusCode = "stav_posudku_1"
                        });
                });

            modelBuilder.Entity("Elp.Domain.Entities.FitnessGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverFitnessCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverFitnessCertificateId");

                    b.ToTable("FitnessGroups");
                });

            modelBuilder.Entity("Elp.Domain.Entities.CodebookItem", b =>
                {
                    b.HasOne("Elp.Domain.Entities.Codebook", "Codebook")
                        .WithMany("Items")
                        .HasForeignKey("CodebookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Codebook");
                });

            modelBuilder.Entity("Elp.Domain.Entities.FitnessGroup", b =>
                {
                    b.HasOne("Elp.Domain.Entities.DriverFitnessCertificate", "Certificate")
                        .WithMany("FitnessGroups")
                        .HasForeignKey("DriverFitnessCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Elp.Domain.Entities.Codebook", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Elp.Domain.Entities.DriverFitnessCertificate", b =>
                {
                    b.Navigation("FitnessGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
