// <auto-generated />
using System;
using Elp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415030307_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elp.Domain.Entities.Codebook", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameCz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Codebooks");

                    b.HasData(
                        new
                        {
                            Code = "StavPosudku",
                            NameCz = "Stavy lékařských posudků",
                            NameEn = "Medical Certificate Statuses"
                        },
                        new
                        {
                            Code = "TypOpravneni",
                            NameCz = "Typy řidičských oprávnění",
                            NameEn = "Driving License Types"
                        });
                });

            modelBuilder.Entity("Elp.Domain.Entities.CodebookItem", b =>
                {
                    b.Property<string>("CodebookCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescriptionCz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CodebookCode", "Code");

                    b.ToTable("CodebookItems");

                    b.HasData(
                        new
                        {
                            CodebookCode = "StavPosudku",
                            Code = "VYDANO",
                            DescriptionCz = "Posudek byl vydán",
                            DescriptionEn = "Certificate Issued",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "StavPosudku",
                            Code = "ZAMITNUTO",
                            DescriptionCz = "Posudek byl zamítnut",
                            DescriptionEn = "Certificate Rejected",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "StavPosudku",
                            Code = "ZNEPLATNENO",
                            DescriptionCz = "Posudek byl zneplatněn",
                            DescriptionEn = "Certificate Invalidated",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "TypOpravneni",
                            Code = "A",
                            DescriptionCz = "Motocykly",
                            DescriptionEn = "Motorcycles",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "TypOpravneni",
                            Code = "B",
                            DescriptionCz = "Osobní automobily",
                            DescriptionEn = "Passenger cars",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "TypOpravneni",
                            Code = "C",
                            DescriptionCz = "Nákladní automobily",
                            DescriptionEn = "Trucks",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "TypOpravneni",
                            Code = "D",
                            DescriptionCz = "Autobusy",
                            DescriptionEn = "Buses",
                            IsActive = true
                        },
                        new
                        {
                            CodebookCode = "TypOpravneni",
                            Code = "T",
                            DescriptionCz = "Traktory",
                            DescriptionEn = "Tractors",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Elp.Domain.Entities.DriverFitnessCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicalProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverFitnessCertificates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IssueDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PersonalId = "ABC-123-456",
                            StatusCode = "VYDANO"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            IssueDate = new DateTime(2026, 2, 10, 9, 30, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PersonalId = "XYZ-987-654",
                            StatusCode = "ZAMITNUTO"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            IssueDate = new DateTime(2020, 5, 20, 14, 15, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PersonalId = "ABC-123-456",
                            StatusCode = "ZNEPLATNENO"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            IssueDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MedicalProfessionalId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PersonalId = "LMN-456-789",
                            StatusCode = "VYDANO"
                        });
                });

            modelBuilder.Entity("Elp.Domain.Entities.FitnessGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverFitnessCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverFitnessCertificateId");

                    b.ToTable("FitnessGroups");
                });

            modelBuilder.Entity("Elp.Domain.Entities.CodebookItem", b =>
                {
                    b.HasOne("Elp.Domain.Entities.Codebook", "Codebook")
                        .WithMany("Items")
                        .HasForeignKey("CodebookCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Codebook");
                });

            modelBuilder.Entity("Elp.Domain.Entities.FitnessGroup", b =>
                {
                    b.HasOne("Elp.Domain.Entities.DriverFitnessCertificate", "Certificate")
                        .WithMany("FitnessGroups")
                        .HasForeignKey("DriverFitnessCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Elp.Domain.Entities.Codebook", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Elp.Domain.Entities.DriverFitnessCertificate", b =>
                {
                    b.Navigation("FitnessGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
